### ISSUE TITLE
Adding support for doors and outputs

### ISSUE THREAD

**Issue by termdude** [mbrrg/pyspcwebgw#1]
According to the specification, doors and outputs are supported in the SPC Web Gateway software. It also seems quit simple to implement. I'm really not a programmer though, but I can help debug. I run the SPC Web Gateway using four doors.

**Comment by crallian** [comment]
Outputs: working on at least reading them, lets see how difficult it is to set them given the class structure.
Unfortunately I dont have any doors myself, and being new to HA I dont easily see how they should be implemented with so many attributes (DPS/DRS/status/mode).

**Comment by crallian** [comment]
Unfortunately I found that an Output status change doesn't send a SIA code over the EDP protocol, so status changed could not be pushed as for the other functions implemented. However, Technical zones are now supported (from 0.106), and from SPC fw 3.11 virtual zones can be created. This can be used as a workaround to track the status of an output as a binary sensor.

**Comment by mbrrg** [comment]
Closed because of protocol limitations.
